### ISSUE TITLE
Single-threaded time synchronization performance regression

### ISSUE THREAD

**Issue by SoftExpert** [pendulum-project/ntpd-rs#1778]
Hello,

I built from source and installed locally **ntpd-rs**; with the release of version **1.4.0** I was expecting that the number of threads would be reduced to 1 (I'm using it as an NTP client).
However, there are still as many threads as there are cores:

```
❯ lscpu
Architecture:             x86_64
  CPU op-mode(s):         32-bit, 64-bit
  Address sizes:          48 bits physical, 48 bits virtual
  Byte Order:             Little Endian
CPU(s):                   16
  On-line CPU(s) list:    0-15
Vendor ID:                AuthenticAMD
  Model name:             AMD Ryzen 7 8700G w/ Radeon 780M Graphics
    CPU family:           25
    Model:                117
    Thread(s) per core:   2
    Core(s) per socket:   8
    Socket(s):            1
    Stepping:             2


❯ pstree -p `pidof ntp-daemon`
ntp-daemon(927)─┬─{ntp-daemon}(929)
                ├─{ntp-daemon}(930)
                ├─{ntp-daemon}(931)
                ├─{ntp-daemon}(932)
                ├─{ntp-daemon}(933)
                ├─{ntp-daemon}(934)
                ├─{ntp-daemon}(935)
                ├─{ntp-daemon}(936)
                ├─{ntp-daemon}(937)
                ├─{ntp-daemon}(938)
                ├─{ntp-daemon}(939)
                ├─{ntp-daemon}(940)
                ├─{ntp-daemon}(941)
                ├─{ntp-daemon}(942)
                ├─{ntp-daemon}(943)
                ├─{ntp-daemon}(944)
                └─{ntp-daemon}(945)
```

My config file looks like this:
```toml
❯ cat ntp.toml 
[observability]
# You can configure ntpd-rs with different output levels of logging information
# Basic values for this are `trace`, `debug`, `info`, `warn` and `error`.
log-level = "info"
## Using the observe socket you can retrieve statistical information about the
## daemon while it is running. You can use the `ntp-ctl` or prometheus based
## `ntp-metrics-exporter` binaries for some default options to read from the
## observe socket.
observation-path = "/var/run/ntpd-rs/observe"

## The sources section allows configuring sources, you may configure multiple of
## these blocks to add more sources to your configuration.
## Our default configuration spawns a pool of sources (by default this attempts
## to discover 4 distinct sources).
[[source]]
mode = "pool"
address = "ntpd-rs.pool.ntp.org"
count = 4

[[source]]
mode = "pool"
address = "ntp.time.nl"
count = 2


## If you have an NTS server, you can configure a source that connects using NTS
## by adding a configuration such as the one below
[[source]]
mode = "nts"
# NTS service from NETNOD: https://www.netnod.se/nts/network-time-security
address = "nts.netnod.se"

## A source in server mode will only create a single source in contrast to the
## multiple sources of a pool. This is the recommended source mode if you only
## have an IP address for your source.
#[[source]]
#mode = "server"
#address = "ntpd-rs.pool.ntp.org"

## If you want to provide time to other machines, the configuration below
## enables serving time on port 123 of all network interfaces.
#[[server]]
#listen = "[::]:123"

## Below are configured various thresholds beyond which ntpd-rs will not
## change the system clock. CHANGE THESE TO MATCH YOUR SECURITY NEEDS!
[synchronization]
# The maximum step size (in seconds) of a single step during normal operation
single-step-panic-threshold = 1800
# On startup a larger jump may occur, this sets limits for that initial jump
startup-step-panic-threshold = { forward="inf", backward = 86400 }
# If, during the lifetime of the ntp-daemon the combined time of time jumps
# exceeds this value, then the NTP daemon will stop, this is disabled by default
#accumulated-threshold = 1800
#minimum-agreeing-sources = 3

```

What am I missing? 
Is there something wrong / missing in my configuration or the [change](https://github.com/pendulum-project/ntpd-rs/pull/1756) has not yet been integrated in the released version ?
