### ISSUE TITLE
peer less server configuration

### ISSUE THREAD

**Issue by tq-steina** [pendulum-project/ntpd-rs#771]
I'm using `ntpd-rs` as a local NTP server for my embedded systems during development. Regularly these devices don't have a battery powered RTC, so NTP is required for startup.

As they are connected on a dedicated network, there is no access to the regular NTP server. For this reason I wan't to provide my local system time on (local) NTP server. Accuracy is not needed anyway.

For now I have to configure my regular NTP server in `peers = ["my.regular.ntp.server.example.com"]` in order to get `ntpd-rs` to create an UDP socket on port 123. If `peers` is empty there is no UDP socket on port 123.

Fun fact: the configured NTP peer (see above) is ignored anyway:
> WARN ntp_proto::peer: Peer rejected due to invalid stratum stratum=16

How can I configure a NTP server without any peers?

**Comment by davidv1992** [comment]
Could you give us the entire config you are using? Just adding the peers= line shouldn't matter for whether the server part starts.

**Comment by tq-steina** [comment]
Thanks for the fast response. I was assuming the same that `peers=[]` should work as well, but `netstat -pn` doesnt list the udp port. That's my config, with comments removed:
```toml
log-filter = "info"
log-format = "full"
peers = ["de.ntp.tq-net.de"]
#peers = []

[[server]]
addr = "[::]:123"

[system]
min-intersection-survivors = 0
panic-threshold = 10
startup-panic-threshold = { forward = 0, backward = 1800 }
local-stratum = 8

[observe]
path = "/run/ntpd-rs/observe"
```
